//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayudante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ayudante()
        {
            this.HojaDeRuta = new HashSet<HojaDeRuta>();
        }
    
        public int IDAyudate { get; set; }
        public string NombreAyudante { get; set; }
        public string ApellidoAyudante { get; set; }
        public string DNIAyudante { get; set; }
        public string DireccionAyudante { get; set; }
        public string TelefonoAyudante { get; set; }
        public string CelularAyudante { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HojaDeRuta> HojaDeRuta { get; set; }
    }
}
