//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bckp_vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bckp_vehiculo()
        {
            this.HojaDeRuta = new HashSet<HojaDeRuta>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int IDVehiculo { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Tipo { get; set; }
        public string Placa { get; set; }
        public System.DateTime SoatFechaInic { get; set; }
        public System.DateTime SoatFechVenc { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> Volumen { get; set; }
        public Nullable<System.DateTime> FechaDeInicioRevisionTecn { get; set; }
        public Nullable<System.DateTime> FechaDeCaducidadReviciTecni { get; set; }
        public Nullable<System.DateTime> FechaIncioSeguroVehicular { get; set; }
        public Nullable<System.DateTime> FechaCaducidadSeguVehicu { get; set; }
        public string NumeroHabilitacion { get; set; }
        public Nullable<System.DateTime> FechaInicioCertificadoFumiga { get; set; }
        public Nullable<System.DateTime> FechaCaducidadCertificadoFumiga { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HojaDeRuta> HojaDeRuta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
