//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chofer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chofer()
        {
            this.HojaDeRuta = new HashSet<HojaDeRuta>();
        }
    
        public int IDchofer { get; set; }
        public string NombreChofer { get; set; }
        public string ApellidosChofer { get; set; }
        public string DNIChofer { get; set; }
        public string FuncionChofer { get; set; }
        public string NumeroBreveteChofer { get; set; }
        public System.DateTime FechaDActivacionBrevete { get; set; }
        public System.DateTime FecchaVencimientoBrevete { get; set; }
        public string CelularPersonalChofer { get; set; }
        public string CelularCorporativoChofer { get; set; }
        public string EmailChofer { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HojaDeRuta> HojaDeRuta { get; set; }
    }
}
