//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int IDContactos { get; set; }
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Celular { get; set; }
        public string EmailContacto { get; set; }
        public int IDEmpresa { get; set; }
        public string Estado { get; set; }
    
        public virtual EmpresaCliente EmpresaCliente { get; set; }
    }
}
