//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Observacion
    {
        public int IDObservaciones { get; set; }
        public int IDHojaDeRuta { get; set; }
        public string DescripcionDObservacion { get; set; }
    
        public virtual HojaDeRuta HojaDeRuta { get; set; }
    }
}
