//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisionTecnica
    {
        public int RevisionTecnicaId { get; set; }
        public int VehiculoId { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<System.DateTime> FecEmisionSeguro { get; set; }
        public Nullable<System.DateTime> FecCaducidadSeguro { get; set; }
        public Nullable<System.DateTime> FecEmisionCertiFumiga { get; set; }
        public Nullable<System.DateTime> FecCaducidadCertiFumiga { get; set; }
        public string Estado { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
