//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soat
    {
        public int SoatId { get; set; }
        public int VehiculoId { get; set; }
        public string Numero { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCaducidad { get; set; }
        public string Estado { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
