//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transporto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_TRANSPORTOEntities : DbContext
    {
        public BD_TRANSPORTOEntities()
            : base("name=BD_TRANSPORTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayudante> Ayudante { get; set; }
        public virtual DbSet<Chofer> Chofer { get; set; }
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<EmpresaCliente> EmpresaCliente { get; set; }
        public virtual DbSet<HojaDeRuta> HojaDeRuta { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Observacion> Observacion { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<RolesDeUsuario> RolesDeUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
    }
}
